version: '3.8'
services:

  postgres:
    image: postgres
    container_name: prisma_tuts
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - application_network

volumes:
  postgres:

networks:
  application_network: